In [1]:
import numpy as np
import  pandas as pd
import string
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import  accuracy_score, classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer,TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import joblib

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
dataframe = pd.read_csv("C:/Users/Admin/Desktop/PROJECT/dataset1.csv")
dataframe.head()

text verified  review_score  \
0  I had received my copy of this new version of ...     True             3   
1  That ever since i purchased my DS when it was ...    False             5   
2          Simple, and just a bit goes a long way..      True             5   
3  I have not played any of the other games in th...     True             4   
4  i got it quick and it was in great shape works...     True             5   

      product_category  
0          video_games  
1          video_games  
2  musical_instruments  
3          video_games  
4          video_games

In [8]:
np.shape(dataframe)

(23962, 4)

In [4]:
dataframe.dropna(inplace=True)  # dropping all rows having atleast 1 missing value
dataframe.head()

text verified  review_score  \
0  I had received my copy of this new version of ...     True             3   
1  That ever since i purchased my DS when it was ...    False             5   
2          Simple, and just a bit goes a long way..      True             5   
3  I have not played any of the other games in th...     True             4   
4  i got it quick and it was in great shape works...     True             5   

      product_category  
0          video_games  
1          video_games  
2  musical_instruments  
3          video_games  
4          video_games

In [10]:
np.shape(dataframe)

(23221, 4)

In [5]:
label_encoder = LabelEncoder()
dataframe['verified'] = label_encoder.fit_transform(dataframe['verified'])
dataframe.head()

text  verified  review_score  \
0  I had received my copy of this new version of ...         1             3   
1  That ever since i purchased my DS when it was ...         0             5   
2          Simple, and just a bit goes a long way..          1             5   
3  I have not played any of the other games in th...         1             4   
4  i got it quick and it was in great shape works...         1             5   

      product_category  
0          video_games  
1          video_games  
2  musical_instruments  
3          video_games  
4          video_games

In [6]:
x_train, x_test, y_train, y_test = train_test_split(dataframe['text'],dataframe['verified'],test_size=0.20, random_state = 42)

In [7]:
y_train=y_train.astype(int)

In [8]:
y_test = y_test.astype(int)

In [10]:
x_train

22978        Oh come on, who doesn't love this game?!. GTA
21284    This would have been the perfect cover-plate o...
1195     If nothing else, Just Dance is consistent.\n\n...
5746                 Nice add for your FLY3 Blackstar Amp.
17505    EASILY the best Sonic game since Sonic & Knuck...
                               ...                        
12372    Had one for about a year or two, and it died. ...
22261    it is one of my favorite games of all time, if...
5571                            NOT GOOD FOR HEAVY LIGHTS.
883      I put this in my Xbox 360 Wired Controller. I ...
16307    I just recently starting playing The Sims (the...
Name: text, Length: 18576, dtype: object

In [11]:
y_train

22978    1
21284    1
1195     0
5746     1
17505    1
        ..
12372    1
22261    1
5571     1
883      1
16307    0
Name: verified, Length: 18576, dtype: int32

In [12]:
x_test

4701     The Age of Empire II expansion is, of course, ...
6971     As always, nintendo may not be doing the whole...
1943     I bought this to try out on my baritone uke.\n...
20090    I bought this game even without having played ...
11302    Good quality cable and very quiet. Just what I...
                               ...                        
10372    Okay, I have been hesitant to buy this since d...
20002    Don't get me wrong, the game is entertaining. ...
17915                                            Good fun.
11430    So I ordered this guy less than a year ago, on...
2180     this review is for the ps4 and the arkham knig...
Name: text, Length: 4645, dtype: object

In [13]:
y_test

4701     0
6971     0
1943     0
20090    0
11302    1
        ..
10372    1
20002    1
17915    1
11430    0
2180     1
Name: verified, Length: 4645, dtype: int32

In [9]:
def convertmyTxt(rv):
    np = [c for c in rv if c not in string.punctuation]
    np = ''.join(np)
    return [w for w in np.split() if w.lower() not in stopwords.words('english')]

In [15]:
pip = Pipeline([
    ('bow',CountVectorizer(analyzer=convertmyTxt)),
    ('tfidf',TfidfTransformer()),
    ('classifier',RandomForestClassifier())
])

In [19]:
pip.fit(x_train,y_train)

Pipeline(steps=[('bow',
                 CountVectorizer(analyzer=<function convertmyTxt at 0x000002C2A49A63E0>)),
                ('tfidf', TfidfTransformer()),
                ('classifier', RandomForestClassifier())])

In [ ]:
randomForestClassifier = pip.predict(x_test)
randomForestClassifier

array([0, 1, 1, ..., 1, 1, 1])

In [ ]:
print('Accuracy of the RF model: ',str(np.round(accuracy_score(y_test,randomForestClassifier)*100,2)) + '%')

Accuracy of the RF model:  79.96%


In [16]:
pip = Pipeline([
    ('bow',CountVectorizer(analyzer=convertmyTxt)),
    ('tfidf',TfidfTransformer()),
    ('classifier',SVC())
])

In [ ]:
pip.fit(x_train,y_train)

Pipeline(steps=[('bow',
                 CountVectorizer(analyzer=<function convertmyTxt at 0x79f48dc5aef0>)),
                ('tfidf', TfidfTransformer()), ('classifier', SVC())])

In [ ]:
supportVectorClassifier = pip.predict(x_test)
supportVectorClassifier

array([0, 1, 1, ..., 1, 1, 1])

In [ ]:
print('accuracy of the SVC model:',str(np.round(accuracy_score(y_test,supportVectorClassifier)*100,2)) + '%')

accuracy of the SVC model: 81.23%


In [ ]:
pip = Pipeline([
    ('bow',CountVectorizer(analyzer=convertmyTxt)),
    ('tfidf',TfidfTransformer()),
    ('classifier',LogisticRegression())
])

In [ ]:
pip.fit(x_train,y_train)

Pipeline(steps=[('bow',
                 CountVectorizer(analyzer=<function convertmyTxt at 0x78e9c0bdd870>)),
                ('tfidf', TfidfTransformer()),
                ('classifier', LogisticRegression())])

In [ ]:
logisticRegression = pip.predict(x_test)
logisticRegression

array([0, 1, 1, ..., 1, 1, 1])

In [ ]:
print('accuracy of the LR model:',str(np.round(accuracy_score(y_test,logisticRegression)*100,2)) + '%')

accuracy of the LR model: 80.22%


In [11]:
vectorizer = TfidfVectorizer(sublinear_tf=True,use_idf=True)
train_vectors = vectorizer.fit_transform(x_train)
test_vectors = vectorizer.transform(x_test)

In [18]:
train_vectors

<18576x39497 sparse matrix of type '<class 'numpy.float64'>'
	with 1230120 stored elements in Compressed Sparse Row format>

In [19]:
test_vectors

<4645x39497 sparse matrix of type '<class 'numpy.float64'>'
	with 296294 stored elements in Compressed Sparse Row format>

In [16]:
# Training SVM model
model = SVC(kernel='linear', C=1.0, gamma='auto')
model.fit(train_vectors, y_train)
result = model.predict(test_vectors)

In [21]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

           0       0.71      0.55      0.62      1294
           1       0.84      0.91      0.88      3351

    accuracy                           0.81      4645
   macro avg       0.77      0.73      0.75      4645
weighted avg       0.80      0.81      0.80      4645



In [ ]:
import optuna
def objective(trial):
    C = trial.suggest_loguniform('C', 0.01, 100)
    gamma = trial.suggest_loguniform('gamma', 0.0001, 10)

    model = SVC(kernel='linear', C=C, gamma=gamma)
    model.fit(train_vectors, y_train)

    result = model.predict(test_vectors)
    accuracy = accuracy_score(y_test, result)


    return accuracy

In [ ]:
study = optuna.create_study(direction = 'maximize')
study.optimize(objective, n_trials=5)

[I 2023-12-20 07:28:07,159] A new study created in memory with name: no-name-d4955f3c-311e-4927-8eff-2ffb2f4ac7d1
<ipython-input-20-7f442a7b9f75>:3: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('C', 0.01, 100)
<ipython-input-20-7f442a7b9f75>:4: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  gamma = trial.suggest_loguniform('gamma', 0.0001, 10)
[I 2023-12-20 07:30:46,061] Trial 0 finished with value: 0.7911733046286329 and parameters: {'C': 0.03925552827498419, 'gamma': 3.427261145230834}. Best is trial 0 with value: 0.7911733046286329.
<ipython-input-20-7f442a7b9f75>:3: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This fe

In [ ]:
best_params = study.best_params
model = SVC(kernel='linear', C=best_params['C'], gamma=best_params['gamma'])
model.fit(train_vectors, y_train)
result = model.predict(test_vectors)

SVC(C=0.2910230182686424, gamma=0.15703534406327338, kernel='linear')

In [ ]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

           0       0.72      0.51      0.60      1294
           1       0.83      0.93      0.88      3351

    accuracy                           0.81      4645
   macro avg       0.78      0.72      0.74      4645
weighted avg       0.80      0.81      0.80      4645



In [18]:
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(sublinear_tf=True, use_idf=True)),
    ('classifier', model),
])



pipeline.fit(x_train, y_train)


joblib.dump(pipeline, "svm_model.pkl")


['svm_model.pkl']